# Generated by Django 4.2.7 on 2026-05-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('remind_at', models.DateTimeField()),
                ('repeat', models.CharField(choices=[('none', 'Sin repetición'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='none', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reminders',
                'ordering': ['remind_at'],
            },
        ),
    ]
